var gridAlbumArt = [
  { Title: "Feels",  Year: "2005", Artist: "Animal Collective", Original: "images/projects/grid-album-project/original/animal-collective-01.jpg", Grid: "images/projects/grid-album-project/animal-collective-01.png" },
  { Title: "Wildflower",  Year: "2016", Artist: "The Avalanches", Original: "images/projects/grid-album-project/original/avalanches-01.jpg", Grid: "images/projects/grid-album-project/avalanches-01.png" },
  { Title: "Acid Rap",  Year: "2013", Artist: "Chance the Rapper", Original: "images/projects/grid-album-project/original/chance-the-rapper-01.jpg", Grid: "images/projects/grid-album-project/chance-the-rapper-01.png" },
  { Title: "Kill for Love",  Year: "2012", Artist: "Chromatics", Original: "images/projects/grid-album-project/original/chromatics-01.jpg", Grid: "images/projects/grid-album-project/chromatics-01.png" },
  { Title: "Sometimes I Sit and Think, and Sometimes I Just Sit",  Year: "2015", Artist: "Courtney Barnett", Original: "images/projects/grid-album-project/original/courtney-barnett-01.jpg", Grid: "images/projects/grid-album-project/courtney-barnett-01.png" },
  { Title: "Let's Dance",  Year: "1983", Artist: "David Bowie", Original: "images/projects/grid-album-project/original/david-bowie-01.jpg", Grid: "images/projects/grid-album-project/david-bowie-01.png" },
  { Title: "Bitte Orca",  Year: "2009", Artist: "Dirty Projectors", Original: "images/projects/grid-album-project/original/dirty-projectors-01.jpg", Grid: "images/projects/grid-album-project/dirty-projectors-01.png" },
  { Title: "Get to Heaven",  Year: "2016", Artist: "Everything Everything", Original: "images/projects/grid-album-project/original/everything-everything-02.jpg", Grid: "images/projects/grid-album-project/everything-everything-02.png" },
  { Title: "Fear Fun",  Year: "2012", Artist: "Father John Misty", Original: "images/projects/grid-album-project/original/father-john-01.jpg", Grid: "images/projects/grid-album-project/father-john-01.png" },
  { Title: "I Love You, Honeybear",  Year: "2015", Artist: "Father John Misty", Original: "images/projects/grid-album-project/original/father-john-02.jpg", Grid: "images/projects/grid-album-project/father-john-02.png" },
  { Title: "The Terror",  Year: "2013", Artist: "The Flaming Lips", Original: "images/projects/grid-album-project/original/flaming-lips-01.jpg", Grid: "images/projects/grid-album-project/flaming-lips-01.png" },
  { Title: "channel ORANGE",  Year: "2012", Artist: "Frank Ocean", Original: "images/projects/grid-album-project/original/frank-ocean-01.jpg", Grid: "images/projects/grid-album-project/frank-ocean-01.png" },
  { Title: "Blonde",  Year: "2016", Artist: "Frank Ocean", Original: "images/projects/grid-album-project/original/frank-ocean-02.jpeg", Grid: "images/projects/grid-album-project/frank-ocean-02.png" },
  { Title: "Album",  Year: "2009", Artist: "Girls", Original: "images/projects/grid-album-project/original/girls-01.jpg", Grid: "images/projects/grid-album-project/girls-01.png" },
  { Title: "Broken Dreams Club",  Year: "2010", Artist: "Girls", Original: "images/projects/grid-album-project/original/girls-02.jpg", Grid: "images/projects/grid-album-project/girls-02.png" },
  { Title: "Lift Your Skinny Fists Like Antennas to Heaven",  Year: "2000", Artist: "Godspeed You! Black Emperor", Original: "images/projects/grid-album-project/original/godspeed-01.jpg", Grid: "images/projects/grid-album-project/godspeed-01.png" },
  { Title: "Painted Shut",  Year: "2015", Artist: "Hop Along", Original: "images/projects/grid-album-project/original/hop-along-02.jpg", Grid: "images/projects/grid-album-project/hop-along-02.png" },
  { Title: "Hozier",  Year: "2014", Artist: "Hozier", Original: "images/projects/grid-album-project/original/hozier-01.jpg", Grid: "images/projects/grid-album-project/hozier-01.png" },
  { Title: "The Shepherd's Dog",  Year: "2007", Artist: "Iron & Wine", Original: "images/projects/grid-album-project/original/iron-wine-01.jpg", Grid: "images/projects/grid-album-project/iron-wine-01.png" },
  { Title: "In Colour",  Year: "2015", Artist: "Jaime xx", Original: "images/projects/grid-album-project/original/jaimie-xx-01.jpg", Grid: "images/projects/grid-album-project/jaimie-xx-01.png" },
  { Title: "Only One",  Year: "2015", Artist: "Kanye West", Original: "images/projects/grid-album-project/original/kanye-west-01.jpg", Grid: "images/projects/grid-album-project/kanye-west-01.png" },
  { Title: "Congratulations",  Year: "2010", Artist: "MGMT", Original: "images/projects/grid-album-project/original/mgmt-01.jpg", Grid: "images/projects/grid-album-project/mgmt-01.png" },
  { Title: "Exile Vilify (From the Game Portal 2) - Single",  Year: "2011", Artist: "The National", Original: "images/projects/grid-album-project/original/national-01.jpeg", Grid: "images/projects/grid-album-project/national-01.png" },
  { Title: "Brill Bruisers",  Year: "2014", Artist: "The New Pornographers", Original: "images/projects/grid-album-project/original/new-pornographers-01.jpg", Grid: "images/projects/grid-album-project/new-pornographers-01.png" },
  { Title: "Nevermind",  Year: "1991", Artist: "Nirvana", Original: "images/projects/grid-album-project/original/nirvana-01.jpg", Grid: "images/projects/grid-album-project/nirvana-01.png" },
  { Title: "Human Performance",  Year: "2016", Artist: "Parquet Courts", Original: "images/projects/grid-album-project/original/parquet-courts-01.jpg", Grid: "images/projects/grid-album-project/parquet-courts-01.png" },
  { Title: "Bankrupt!",  Year: "2013", Artist: "Phoenix", Original: "images/projects/grid-album-project/original/phoenix-01.jpg", Grid: "images/projects/grid-album-project/phoenix-01.png" },
  { Title: "Third",  Year: "2008", Artist: "Portishead", Original: "images/projects/grid-album-project/original/portishead-01.png", Grid: "images/projects/grid-album-project/portishead-01.png" },
  { Title: "The Satanic Satanist",  Year: "2009", Artist: "Portugal. The Man", Original: "images/projects/grid-album-project/original/portugal-the-man-01.jpg", Grid: "images/projects/grid-album-project/portugal-the-man-01.png" },
  { Title: "Actor",  Year: "2009", Artist: "St. Vincent", Original: "images/projects/grid-album-project/original/st-vincent-01.jpg", Grid: "images/projects/grid-album-project/st-vincent-01.png" },
  { Title: "Wig Out at Jagbags",  Year: "2014", Artist: "Stephen Malkus & The Jicks", Original: "images/projects/grid-album-project/original/stephen-malkus-01.jpg", Grid: "images/projects/grid-album-project/stephen-malkus-01.png" },
  { Title: "Room on Fire",  Year: "2003", Artist: "The Strokes", Original: "images/projects/grid-album-project/original/strokes-02.jpg", Grid: "images/projects/grid-album-project/strokes-02.png" },
  { Title: "Angles",  Year: "2011", Artist: "The Strokes", Original: "images/projects/grid-album-project/original/strokes-04.jpg", Grid: "images/projects/grid-album-project/strokes-04.png" },
  { Title: "Comedown Machine",  Year: "2013", Artist: "The Strokes", Original: "images/projects/grid-album-project/original/strokes-05.jpg", Grid: "images/projects/grid-album-project/strokes-05.png" },
  { Title: "The Wild Hunt",  Year: "2010", Artist: "The Tallest Man on Earth", Original: "images/projects/grid-album-project/original/tallest-man-on-earth-01.jpg", Grid: "images/projects/grid-album-project/tallest-man-on-earth-01.png" },
  { Title: "Marquee Moon",  Year: "1977", Artist: "Television", Original: "images/projects/grid-album-project/original/television-01.jpg", Grid: "images/projects/grid-album-project/television-01.png" },
  { Title: "Star Wars",  Year: "2015", Artist: "Wilco", Original: "images/projects/grid-album-project/original/wilco-01.jpg", Grid: "images/projects/grid-album-project/wilco-01.png" },
  { Title: "Coexist",  Year: "2012", Artist: "The xx", Original: "images/projects/grid-album-project/original/xx-02.jpg", Grid: "images/projects/grid-album-project/xx-02.png" },
];
